# Generated by Django 2.1.4 on 2019-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190514_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ac_type',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comp_name',
            field=models.CharField(max_length=30),
        ),
    ]
