# Generated by Django 2.1.4 on 2019-05-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ac_type',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='comp_name',
            new_name='company_name',
        ),
    ]
