# Generated by Django 2.1.4 on 2019-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190517_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(max_length=500),
        ),
    ]
