# Generated by Django 2.2.7 on 2020-02-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='creationDate',
        ),
    ]
