# Generated by Django 2.1.4 on 2019-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
