# Generated by Django 2.1.4 on 2019-05-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_tender', '0001_initial'),
        ('core', '0008_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote_amount', models.PositiveIntegerField()),
                ('Bid_description', models.TextField(max_length=500)),
                ('Bid_documents_url', models.FileField(upload_to='')),
                ('Bid_created_date', models.DateField(auto_now_add=True)),
                ('Tender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tender.CreateTender')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
    ]
