# Generated by Django 2.1.4 on 2019-05-26 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0002_auto_20190525_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_documents_url',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default='betts', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
