# Generated by Django 2.1.4 on 2019-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0004_auto_20190530_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_documents_url',
            field=models.FileField(upload_to=''),
        ),
    ]
