# Generated by Django 2.1.4 on 2019-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0006_auto_20190530_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_documents_url',
            field=models.FilePathField(blank=True),
        ),
    ]
