# Generated by Django 2.1.4 on 2019-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0007_auto_20190531_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_documents_url',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
