# Generated by Django 2.1.4 on 2019-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0008_auto_20190531_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_documents_url',
            field=models.FileField(blank=True, null=True, upload_to='bid/documents/'),
        ),
    ]
