# Generated by Django 2.1.4 on 2019-06-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0008_auto_20190614_1415'),
        ('create_bids', '0009_auto_20190531_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote_amount', models.PositiveIntegerField()),
                ('Product', models.CharField(max_length=120)),
                ('Processor', models.CharField(max_length=120)),
                ('Operating_system', models.CharField(max_length=80)),
                ('Memory', models.CharField(max_length=100)),
                ('Storage', models.CharField(max_length=100)),
                ('Graphics', models.CharField(max_length=100)),
                ('tender_award', models.CharField(default='No', max_length=10)),
                ('date_created', models.DateField(auto_now=True)),
                ('Bid_documents_url', models.FileField(blank=True, null=True, upload_to='bid/documents/')),
                ('Tender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tender.Desktop_Tender')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
