# Generated by Django 2.1.4 on 2019-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0010_desktopbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
