# Generated by Django 2.1.4 on 2019-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0012_remove_desktopbid_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='tender_award',
        ),
    ]
