# Generated by Django 2.1.4 on 2019-06-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0014_furnituretender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_bids', '0013_remove_desktopbid_tender_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mod', models.CharField(max_length=80)),
                ('Net_power', models.CharField(max_length=80)),
                ('Electric', models.CharField(max_length=80)),
                ('Engine', models.CharField(default='No', max_length=80)),
                ('Operating_weight', models.CharField(max_length=80)),
                ('Certification', models.CharField(max_length=80)),
                ('Quote_amount', models.PositiveIntegerField()),
                ('bid_award', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('Bid_documents_url', models.FileField(blank=True, null=True, upload_to='bid/documents/')),
                ('Tender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tender.Tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='FurnitureBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Dimensions', models.CharField(max_length=80)),
                ('Material', models.CharField(max_length=80)),
                ('Color', models.CharField(max_length=80)),
                ('Quote_amount', models.PositiveIntegerField()),
                ('tender_award', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('Bid_documents_url', models.FileField(blank=True, null=True, upload_to='bid/documents/')),
                ('Tender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tender.Tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='bid_award',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='user',
            field=models.ForeignKey(default='brianbett', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
