# Generated by Django 2.1.4 on 2019-06-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0015_auto_20190614_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionbid',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='constructionbid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constbidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='Tender_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deskbidder', to='create_tender.Desktop_Tender'),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
