# Generated by Django 2.1.4 on 2019-06-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0017_auto_20190615_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopbid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
