# Generated by Django 2.1.4 on 2019-06-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0018_auto_20190617_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopbid',
            name='Tender_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tender.Desktop_Tender'),
        ),
    ]
