# Generated by Django 2.1.4 on 2019-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0022_auto_20190617_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniturebid',
            name='tender_award',
        ),
        migrations.AddField(
            model_name='furniturebid',
            name='bid_award',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='constructionbid',
            name='bid_award',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='bid_award',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
