# Generated by Django 2.1.4 on 2019-05-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0002_auto_20190524_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createtender',
            old_name='seller_id',
            new_name='user',
        ),
    ]
