# Generated by Django 2.1.4 on 2019-05-25 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_bids', '0001_initial'),
        ('create_tender', '0004_auto_20190524_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateTender',
            new_name='Tender',
        ),
    ]
