# Generated by Django 2.1.4 on 2019-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0005_auto_20190525_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tender_award',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
