# Generated by Django 2.1.4 on 2019-06-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0007_auto_20190614_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desktop_tender',
            options={'ordering': ['-date_created']},
        ),
    ]
