# Generated by Django 2.1.4 on 2019-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0008_auto_20190614_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_tender',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
