# Generated by Django 2.1.4 on 2019-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0009_desktop_tender_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop_tender',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
