# Generated by Django 2.1.4 on 2019-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tender', '0010_auto_20190614_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop_tender',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
