# Generated by Django 2.1.4 on 2019-06-14 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_tender', '0013_auto_20190614_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Dimensions', models.CharField(max_length=80)),
                ('Material', models.CharField(max_length=80)),
                ('Color', models.CharField(max_length=80)),
                ('Quantity', models.PositiveIntegerField()),
                ('tender_award', models.CharField(default='No', max_length=10)),
                ('date_created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
