# Generated by Django 2.1.4 on 2019-06-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_bids', '0009_auto_20190531_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('bid_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_bids.Bids')),
            ],
        ),
    ]
