# Generated by Django 2.1.4 on 2019-06-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approve_bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptbid',
            name='bid_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_bids.Bids'),
        ),
        migrations.AlterField(
            model_name='acceptbid',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
