# Generated by Django 2.1.4 on 2019-06-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_bids', '0018_auto_20190617_1440'),
        ('approve_bids', '0002_auto_20190609_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptConstBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bid_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_bids.Bids')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptFurnBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bid_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_bids.Bids')),
            ],
        ),
    ]
